name: Watch Activity

on:
  workflow_dispatch:
    inputs:
      stateId:
        description: "State Id"
      eventName:
        description: "Event Name"
      eventPayload:
        description: "Event Payload"
      settings:
        description: "Settings"
      authToken:
        description: "Auth Token"
      ref:
        description: "Ref"
      signature:
        description: "Used for authenticating requests from the kernel."

jobs:
  compute:
    permissions: write-all
    name: User Activity Watcher
    runs-on: ubuntu-latest
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      KERNEL_PUBLIC_KEY: ${{ secrets.KERNEL_PUBLIC_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - run: ${{ toJSON(inputs) }}
        shell: cat {0}

      - name: Watch Activity
        uses: ./
